import { createOptimisticRoutineHook } from "./createOptimisticHook"

import { api } from "@/convex/_generated/api"

/**
 * Optimistic hook for routine priority changes
 *
 * Sets the default priority for tasks generated by this routine
 */
export const useOptimisticRoutinePriority = createOptimisticRoutineHook<[number]>({
  mutationPath: api.routines.internalMutations.updateRoutine.updateRoutine,
  messages: {
    loading: "Updating priority...",
    success: "Priority updated!",
    error: "Failed to update priority"
  },
  createUpdate: (routineId, newPriority) => ({
    routineId,
    type: "priority-change",
    newPriority,
    timestamp: Date.now()
  }),
  createMutationArgs: (routineId, newPriority) => ({
    routineId,
    priority: newPriority
  })
})
