import { createOptimisticRoutineHook } from "./createOptimisticHook"

import { api } from "@/convex/_generated/api"

/**
 * Optimistic hook for routine label changes
 *
 * Sets additional labels for tasks generated by this routine
 * (in addition to the automatic "routine" label)
 */
export const useOptimisticRoutineLabels = createOptimisticRoutineHook<[string[]]>({
  mutationPath: api.routines.internalMutations.updateRoutine.updateRoutine,
  messages: {
    loading: "Updating labels...",
    success: "Labels updated!",
    error: "Failed to update labels"
  },
  createUpdate: (routineId, newLabels) => ({
    routineId,
    type: "label-change",
    newLabels,
    timestamp: Date.now()
  }),
  createMutationArgs: (routineId, newLabels) => ({
    routineId,
    todoistLabels: newLabels
  })
})
