// PROTOTYPE — fixed, realistic fixture data shared by all five design directions.
import type { PrototypeChat, PrototypeMessage } from "./types";

export const prototypeChats: readonly PrototypeChat[] = [
  {
    id: "maya",
    name: "Maya Chen",
    initials: "MC",
    avatarColor: "#C56A54",
    preview: "Can you send the final address before 6?",
    time: "2m",
    unreadCount: 2,
    attention: "reply",
    isGroup: false,
    participants: 1,
    lastFromMe: false,
    pinned: true,
  },
  {
    id: "auf-team",
    name: "AUF Team",
    initials: "AU",
    avatarColor: "#6B74B8",
    preview: "Nico: Updated run of show is in the drive",
    time: "12m",
    unreadCount: 4,
    attention: "reply",
    isGroup: true,
    participants: 6,
    lastFromMe: false,
    pinned: true,
  },
  {
    id: "alex",
    name: "Alex Rivera",
    initials: "AR",
    avatarColor: "#4A8D78",
    preview: "Dinner Thursday works — 8:30?",
    time: "38m",
    unreadCount: 0,
    attention: "reply",
    isGroup: false,
    participants: 1,
    lastFromMe: false,
    pinned: false,
  },
  {
    id: "sam",
    name: "Samir Patel",
    initials: "SP",
    avatarColor: "#92704E",
    preview: "You: I’ll check and get back to you",
    time: "1h",
    unreadCount: 0,
    attention: "waiting",
    isGroup: false,
    participants: 1,
    lastFromMe: true,
    pinned: false,
  },
  {
    id: "warehouse",
    name: "Warehouse Crew",
    initials: "WC",
    avatarColor: "#5C759C",
    preview: "Load-in moved to the east entrance",
    time: "3h",
    unreadCount: 1,
    attention: "clear",
    isGroup: true,
    participants: 9,
    lastFromMe: false,
    pinned: false,
  },
  {
    id: "jules",
    name: "Jules",
    initials: "J",
    avatarColor: "#A95F82",
    preview: "Loved that track you sent",
    time: "Yesterday",
    unreadCount: 0,
    attention: "clear",
    isGroup: false,
    participants: 1,
    lastFromMe: false,
    pinned: false,
  },
  {
    id: "family",
    name: "Family",
    initials: "FM",
    avatarColor: "#588A9A",
    preview: "Mom: Photos from Sunday",
    time: "Tue",
    unreadCount: 0,
    attention: "clear",
    isGroup: true,
    participants: 5,
    lastFromMe: false,
    pinned: false,
  },
  {
    id: "unknown",
    name: "+1 (415) 555-0183",
    initials: "?",
    avatarColor: "#777B82",
    preview: "Hi, following up about your reservation",
    time: "Mon",
    unreadCount: 0,
    attention: "clear",
    isGroup: false,
    participants: 1,
    lastFromMe: false,
    pinned: false,
  },
];

export const prototypeMessages: readonly PrototypeMessage[] = [
  { id: "maya-1", chatId: "maya", text: "Still good for tonight?", time: "5:41 PM", fromMe: false },
  { id: "maya-2", chatId: "maya", text: "Yes — doors are at 8.", time: "5:43 PM", fromMe: true },
  { id: "maya-3", chatId: "maya", text: "Can you send the final address before 6?", time: "5:46 PM", fromMe: false, reaction: "👍" },
  { id: "auf-1", chatId: "auf-team", text: "Updated run of show is in the drive", time: "5:32 PM", fromMe: false, sender: "Nico" },
  { id: "auf-2", chatId: "auf-team", text: "I’ll review the door timing now.", time: "5:34 PM", fromMe: true },
  { id: "alex-1", chatId: "alex", text: "Dinner Thursday works — 8:30?", time: "5:10 PM", fromMe: false },
  { id: "alex-2", chatId: "alex", text: "That should work. Let me confirm the place.", time: "5:14 PM", fromMe: true },
  { id: "sam-1", chatId: "sam", text: "Any word on the permit?", time: "4:21 PM", fromMe: false },
  { id: "sam-2", chatId: "sam", text: "I’ll check and get back to you", time: "4:24 PM", fromMe: true },
  { id: "warehouse-1", chatId: "warehouse", text: "Load-in moved to the east entrance", time: "2:44 PM", fromMe: false, sender: "Devin" },
  { id: "warehouse-2", chatId: "warehouse", text: "Copy. I’ll update the team.", time: "2:51 PM", fromMe: true },
  { id: "jules-1", chatId: "jules", text: "Loved that track you sent", time: "Yesterday", fromMe: false },
  { id: "family-1", chatId: "family", text: "Photos from Sunday", time: "Tuesday", fromMe: false, sender: "Mom" },
  { id: "unknown-1", chatId: "unknown", text: "Hi, following up about your reservation", time: "Monday", fromMe: false },
];
